# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jafri/eosio.contracts/contracts

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jafri/eosio.contracts/contracts

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/jafri/eosio.contracts/contracts && $(CMAKE_COMMAND) -E cmake_progress_start /Users/jafri/eosio.contracts/contracts/CMakeFiles /Users/jafri/eosio.contracts/contracts/tracelytics/CMakeFiles/progress.marks
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 tracelytics/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jafri/eosio.contracts/contracts/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 tracelytics/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 tracelytics/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 tracelytics/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/jafri/eosio.contracts/contracts && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
tracelytics/CMakeFiles/tracelytics.dir/rule:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f CMakeFiles/Makefile2 tracelytics/CMakeFiles/tracelytics.dir/rule
.PHONY : tracelytics/CMakeFiles/tracelytics.dir/rule

# Convenience name for target.
tracelytics: tracelytics/CMakeFiles/tracelytics.dir/rule

.PHONY : tracelytics

# fast build rule for target.
tracelytics/fast:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/build
.PHONY : tracelytics/fast

src/batches.obj: src/batches.cpp.obj

.PHONY : src/batches.obj

# target to build an object file
src/batches.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/batches.cpp.obj
.PHONY : src/batches.cpp.obj

src/batches.i: src/batches.cpp.i

.PHONY : src/batches.i

# target to preprocess a source file
src/batches.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/batches.cpp.i
.PHONY : src/batches.cpp.i

src/batches.s: src/batches.cpp.s

.PHONY : src/batches.s

# target to generate assembly for a file
src/batches.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/batches.cpp.s
.PHONY : src/batches.cpp.s

src/deliveries.obj: src/deliveries.cpp.obj

.PHONY : src/deliveries.obj

# target to build an object file
src/deliveries.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/deliveries.cpp.obj
.PHONY : src/deliveries.cpp.obj

src/deliveries.i: src/deliveries.cpp.i

.PHONY : src/deliveries.i

# target to preprocess a source file
src/deliveries.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/deliveries.cpp.i
.PHONY : src/deliveries.cpp.i

src/deliveries.s: src/deliveries.cpp.s

.PHONY : src/deliveries.s

# target to generate assembly for a file
src/deliveries.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/deliveries.cpp.s
.PHONY : src/deliveries.cpp.s

src/machines.obj: src/machines.cpp.obj

.PHONY : src/machines.obj

# target to build an object file
src/machines.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/machines.cpp.obj
.PHONY : src/machines.cpp.obj

src/machines.i: src/machines.cpp.i

.PHONY : src/machines.i

# target to preprocess a source file
src/machines.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/machines.cpp.i
.PHONY : src/machines.cpp.i

src/machines.s: src/machines.cpp.s

.PHONY : src/machines.s

# target to generate assembly for a file
src/machines.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/machines.cpp.s
.PHONY : src/machines.cpp.s

src/productInstances.obj: src/productInstances.cpp.obj

.PHONY : src/productInstances.obj

# target to build an object file
src/productInstances.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/productInstances.cpp.obj
.PHONY : src/productInstances.cpp.obj

src/productInstances.i: src/productInstances.cpp.i

.PHONY : src/productInstances.i

# target to preprocess a source file
src/productInstances.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/productInstances.cpp.i
.PHONY : src/productInstances.cpp.i

src/productInstances.s: src/productInstances.cpp.s

.PHONY : src/productInstances.s

# target to generate assembly for a file
src/productInstances.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/productInstances.cpp.s
.PHONY : src/productInstances.cpp.s

src/products.obj: src/products.cpp.obj

.PHONY : src/products.obj

# target to build an object file
src/products.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/products.cpp.obj
.PHONY : src/products.cpp.obj

src/products.i: src/products.cpp.i

.PHONY : src/products.i

# target to preprocess a source file
src/products.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/products.cpp.i
.PHONY : src/products.cpp.i

src/products.s: src/products.cpp.s

.PHONY : src/products.s

# target to generate assembly for a file
src/products.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/products.cpp.s
.PHONY : src/products.cpp.s

src/sites.obj: src/sites.cpp.obj

.PHONY : src/sites.obj

# target to build an object file
src/sites.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/sites.cpp.obj
.PHONY : src/sites.cpp.obj

src/sites.i: src/sites.cpp.i

.PHONY : src/sites.i

# target to preprocess a source file
src/sites.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/sites.cpp.i
.PHONY : src/sites.cpp.i

src/sites.s: src/sites.cpp.s

.PHONY : src/sites.s

# target to generate assembly for a file
src/sites.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/sites.cpp.s
.PHONY : src/sites.cpp.s

src/tracelytics.obj: src/tracelytics.cpp.obj

.PHONY : src/tracelytics.obj

# target to build an object file
src/tracelytics.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/tracelytics.cpp.obj
.PHONY : src/tracelytics.cpp.obj

src/tracelytics.i: src/tracelytics.cpp.i

.PHONY : src/tracelytics.i

# target to preprocess a source file
src/tracelytics.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/tracelytics.cpp.i
.PHONY : src/tracelytics.cpp.i

src/tracelytics.s: src/tracelytics.cpp.s

.PHONY : src/tracelytics.s

# target to generate assembly for a file
src/tracelytics.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/tracelytics.cpp.s
.PHONY : src/tracelytics.cpp.s

src/users.obj: src/users.cpp.obj

.PHONY : src/users.obj

# target to build an object file
src/users.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/users.cpp.obj
.PHONY : src/users.cpp.obj

src/users.i: src/users.cpp.i

.PHONY : src/users.i

# target to preprocess a source file
src/users.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/users.cpp.i
.PHONY : src/users.cpp.i

src/users.s: src/users.cpp.s

.PHONY : src/users.s

# target to generate assembly for a file
src/users.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/users.cpp.s
.PHONY : src/users.cpp.s

src/utils.obj: src/utils.cpp.obj

.PHONY : src/utils.obj

# target to build an object file
src/utils.cpp.obj:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/utils.cpp.obj
.PHONY : src/utils.cpp.obj

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	cd /Users/jafri/eosio.contracts/contracts && $(MAKE) -f tracelytics/CMakeFiles/tracelytics.dir/build.make tracelytics/CMakeFiles/tracelytics.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tracelytics"
	@echo "... src/batches.obj"
	@echo "... src/batches.i"
	@echo "... src/batches.s"
	@echo "... src/deliveries.obj"
	@echo "... src/deliveries.i"
	@echo "... src/deliveries.s"
	@echo "... src/machines.obj"
	@echo "... src/machines.i"
	@echo "... src/machines.s"
	@echo "... src/productInstances.obj"
	@echo "... src/productInstances.i"
	@echo "... src/productInstances.s"
	@echo "... src/products.obj"
	@echo "... src/products.i"
	@echo "... src/products.s"
	@echo "... src/sites.obj"
	@echo "... src/sites.i"
	@echo "... src/sites.s"
	@echo "... src/tracelytics.obj"
	@echo "... src/tracelytics.i"
	@echo "... src/tracelytics.s"
	@echo "... src/users.obj"
	@echo "... src/users.i"
	@echo "... src/users.s"
	@echo "... src/utils.obj"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/jafri/eosio.contracts/contracts && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

